name: Manual and Push Build

on:
  push:
    branches:
      - '**'     # Run on push to any branch
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dktanwar/intro_linux
          tags: |
            type=raw,latest
            type=sha

      - name: Log in to Docker Hub
        run: |
          echo "Logging into Docker Hub"
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          platforms: linux/amd64
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
