name: Manual and Push Build

on:
  push:
    branches:
      - '**'  # Run on push to any branch
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (enables multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Generate Docker tags/labels
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dktanwar/intro_linux
          tags: |
            type=raw,latest
            type=sha

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and push Docker image (multi-arch)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
